import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import GoogleMapComponent from '@/components/Map'
import GoogleMapComponent2 from '@/components/Maps'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <GoogleMapComponent apiKey={apiKey} /> */}
        {/* <Map /> */}
        <GoogleMapComponent2 apiKey={apiKey} />
      </main>
    </>
  )
}
